# Generated by Django 4.2.4 on 2024-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_milestone_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("cloud_adresse", models.CharField(max_length=100)),
                ("erp_user", models.CharField(max_length=100)),
                ("erp_pw", models.CharField(max_length=100)),
                ("api_endpoint", models.CharField(max_length=100)),
                ("api_token", models.CharField(max_length=256)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
        ),
    ]
